### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by Shlap1k** [nonamebozoeshkere1488/BRMC-Buckshot-Roulette-Multiplayer-Cheat#1]
How to use it?

**Comment by nonamebozoeshkere1488** [comment]
Start
1. Launch .exe/main.py
2. Launch game
3. Join in multiplayer
4. Host/find lobby(hosting better)
5. After launching multiplayer game. Wait untill logs will be updated(1-20 seconds) and you will see a result
![Buckshot_Roulette_XEhm2HDu8L](https://github.com/user-attachments/assets/60e26c52-b4ac-4e5a-a6fc-8dfeefc65328)
End
1. Close game
2. Close .exe(not command line)/.py(not command line)

**Comment by Shlap1k** [comment]
Can you please make a exe version  of this tool, I can't get it to work?

**Comment by nonamebozoeshkere1488** [comment]
> Can you please make a exe version of this tool, I can't get it to work?

it already exists, in the releases

**Comment by Shlap1k** [comment]
Sorry for bothering you. I figured out what my problem was.

**Comment by nonamebozoeshkere1488** [comment]
> Sorry for bothering you. I figured out what my problem was.

No Problem!
