### ISSUE TITLE
Don't download it, it's a virus

### ISSUE THREAD

**Issue by dent0s** [nonamebozoeshkere1488/BRMC-Buckshot-Roulette-Multiplayer-Cheat#3]
https://www.virustotal.com/gui/file/141d03cf2b01adfbc629bb4bec6277663d3c2cd92eed547411cca81dc181a5d1

**Comment by nonamebozoeshkere1488** [comment]
> https://www.virustotal.com/gui/file/141d03cf2b01adfbc629bb4bec6277663d3c2cd92eed547411cca81dc181a5d1

LOL, BRO JUST COPY THE SOURCE CODE AND LAUNCH IT
its nuitka problem
